# Generated by Django 4.2 on 2023-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("name", models.TextField(default="", max_length=500)),
                ("description", models.TextField(default="", max_length=800)),
            ],
        ),
    ]
