# Generated by Django 4.2 on 2023-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MealMaster_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.TextField(default="", max_length=500)),
            ],
        ),
    ]
