# Generated by Django 4.2 on 2023-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("MealMaster_App", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="meal_master_user_groups",
                to="auth.group",
                verbose_name=("groups",),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text=("_Specific permissions for this user.",),
                related_name="meal_master_user_permission",
                to="auth.permission",
                verbose_name=("_user permissions",),
            ),
        ),
    ]
